class Solution:
    """
    PROBLEM: Given two strings [s, t] string t is generated by 
             random shuffling string s and then add one more letter at a random position
             Return the letter that was added to t... (s + extra_letter).
    FUNCTION: Find and output extra letter from shuffled s.
    PARAMS:   Two strings, s and t
    OUTPUT:   Extra letter added to s (shuffled)
    """
    def findTheDifference(self, s: str, t: str) -> str: 
        # Brute force method
        # loop thru t and check if letter is in str s
        # if yes, continue
        # no, then output letter
        # count matters, good to know
        excluded_from_s = ""
        for ltr in t:
            if ltr not in s or t.count(ltr) > s.count(ltr):
                excluded_from_s = ltr
        return excluded_from_s

if __name__ == '__main__':
    s = "abcd"
    t = "bdcaa"
    test = Solution()
    test.findTheDifference(s, t)